version: 0.2
run-as: root


phases:
  install:
    commands:
      - apt update -y
      - apt install nodejs -y
      - apt install npm -y
  pre_build:
    commands:
      - cd Frontend
  build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - npm i 
      - npm run build
  post_build:
    commands:
      - pwd
      - ls -l
      - cd build
      - ls -l
      - cd
     
