version: 0.2
run-as: root

phases:
  install:
    commands:
      - apt update -y
      - apt install nginx -y
      - apt install nodejs -y
      - apt install npm -y
  pre_build:
    commands:
      - cd Frontend
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  build:
    commands:
      - npm install
      - npm run build

artifacts: 
  files:
    - "**/*"
  discard-paths: yes
  base-directory: Frontend/build
